alterações
keizo13/Flutter pull request #1
Opened 2022-08-24 15:05 UTC by keizo13

2022-08-24 17:51 UTC, keizo13 commented
feito talvez

2022-08-26 12:02 UTC, oliversieto requested changes

2022-08-26 12:02 UTC, oliversieto commented on lib/main.dart
> +      home: Login(),
A primeira página não é o login e sim a Splash.

2022-08-26 12:02 UTC, oliversieto commented on lib/main.dart
> +import 'package:incontre/pages/login.dart';
Seu package é incontre ou first?

2022-08-26 12:02 UTC, oliversieto commented on lib/pages/add.dart
> +              child: TextFormField(
Esse form é desnecessário, pois a API que você criou não tem tag.

2022-08-26 12:02 UTC, oliversieto commented on lib/pages/bottommenu.dart
> +import 'package:incontre/pages/config.dart';
Verificar o package.

2022-08-26 12:02 UTC, oliversieto commented on lib/pages/bottommenu.dart
> +class Bottommenu extends StatefulWidget {
Sempre Camel Case com a primeira letra em maiúsculo.

2022-08-26 12:02 UTC, oliversieto commented on lib/pages/change_password.dart
> +class Change_Password extends StatelessWidget {
Sempre Camel Case e nunca Snake Case

2022-08-26 12:02 UTC, oliversieto commented on lib/pages/edit.dart
> +            Padding(
Nossa API não tem TAG

2022-08-26 12:02 UTC, oliversieto commented on lib/pages/homepage2.dart
> +class Loginempty extends StatelessWidget {
Camel Case

2022-08-26 12:02 UTC, oliversieto commented on lib/pages/login.dart
> +                  hintText: 'senha',
Aqui é e-mail

2022-08-26 14:49 UTC, oliversieto requested changes

2022-08-26 14:49 UTC, oliversieto commented on lib/pages/splash.dart
> +  _navigatetohome() async {
nome de função sempre Camel Case. A função sempre deve ter um tipo de retorno, nesse caso void.

2022-08-26 14:49 UTC, oliversieto commented on lib/pages/splash.dart
> +    Navigator.pushReplacement(
Antes do Navigator adicionar o condicional:
```dart
if (!mounted) {
  return;
}
```
[Link explicando o motivo](https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html)

2022-08-29 13:31 UTC, oliversieto requested changes

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/config.dart
> +          Divider(
Isso aqui seria um bom item para ser um Widget separado.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/homepage.dart
> +                  onTap: (() => {
Procure separar isso em uma função.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/homepage.dart
> +                  fontWeight: FontWeight.bold),
Adicionar vírgula ao final.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/homepage.dart
> +            child: Row(
Transformar isso em um Widget separado.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/login.dart
> +          onTap: () {
Colocar em uma função separada.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_appbar.dart
> +class AppbarEdit extends StatelessWidget implements PreferredSizeWidget {
Bar é com a inicial maiúscula.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_buttom.dart
> +class ButtomEdit extends StatelessWidget {
Pq Edit? A ideia é ser o mais genérico possível.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_buttom.dart
> +  const ButtomEdit({Key? key, required this.title, this.ontap})
Adicionar vírgula ao final.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_buttom.dart
> +          onTap: (() => {}),
A função não está sendo passada aqui.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_buttom.dart
> +                  fontWeight: FontWeight.bold),
Adicionar vírgula.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_input.dart
> +class InputEdit extends StatelessWidget {
Pq Edit?

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_input.dart
> +  const InputEdit({Key? key, required this.title, required this.icon})
Colocar vírgula.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_input.dart
> +            // Icons.person,
remover comentário.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_perfil.dart
> +class PerfilEdit extends StatelessWidget {
Pq Edit?

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_perfil.dart
> +  const PerfilEdit({Key? key, required this.title, required this.route})
Adicionar vírgula.

2022-08-29 13:31 UTC, oliversieto commented on lib/pages/widgets/widget_perfil.dart
> +          Navigator.pushNamed(
Passar para uma função separada.

2022-08-29 19:00 UTC, oliversieto requested changes

2022-08-29 19:00 UTC, oliversieto commented on lib/pages/homepage.dart
> +          Divider(
Utilizar o componente criado.

2022-08-29 19:00 UTC, oliversieto commented on lib/pages/homepage.dart
> +          Divider(
Utilizar o componente criado.

2022-08-29 19:00 UTC, oliversieto commented on lib/pages/widgets/widget_appbar.dart
> +class AppBarEdit extends StatelessWidget implements PreferredSizeWidget {
Pq Edit?

2022-08-29 19:00 UTC, oliversieto commented on lib/pages/widgets/widget_buttom.dart
> +class Buttom extends StatelessWidget {
O correto é Button

2022-08-29 19:00 UTC, oliversieto commented on lib/pages/widgets/widget_divider.dart
> +class AppDivider extends StatelessWidget {
Acredito que Divider será um nome melhor.

2022-08-29 19:00 UTC, oliversieto commented on lib/pages/widgets/widget_list.dart
> +class UserList extends StatelessWidget {
User List é um nome apropriado? É uma lista de usuários?

2022-08-30 11:41 UTC, keizo13 commented on lib/pages/widgets/widget_list.dart
> +class UserList extends StatelessWidget {
sim, é uma lista de usuários

2022-11-21 17:11 UTC, merged